const char* html_template = 
"<!DOCTYPE html><html>"
"<head>"
"  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"  <title>HA Vacuum Control</title>"
"  <style>"
"    body { font-family: sans-serif; background-color: #f4f4f9; padding: 20px; color: #333; }"
"    .container { max-width: 400px; margin: auto; background: white; padding: 25px; border-radius: 12px; box-shadow: 0 4px 10px rgba(0,0,0,0.1); }"
"    h2 { text-align: center; color: #007bff; margin-bottom: 25px; }"
"    label { font-weight: bold; display: block; margin-bottom: 5px; font-size: 0.9em; }"
"    input, select { width: 100%%; padding: 12px; margin-bottom: 20px; border: 1px solid #ccc; border-radius: 6px; box-sizing: border-box; font-size: 16px; }"
"    input[type='submit'] { background-color: #007bff; color: white; border: none; cursor: pointer; font-weight: bold; transition: background 0.3s; }"
"    input[type='submit']:hover { background-color: #0056b3; }"
"    .note { font-size: 0.8em; color: #666; text-align: center; margin-top: 10px; }"
"  </style>"
"</head>"
"<body>"
"  <div class='container'>"
"    <h2>System Setup</h2>"
"    <form action='/save' method='POST'>"
"      %s" // Placeholder for the Wi-Fi Dropdown
"      <label>Wi-Fi Password</label>"
"      <input type='password' name='wifi_pass' placeholder='Enter Wi-Fi Password'>"
"      <hr style='margin-bottom:20px; border:0; border-top:1px solid #eee;'>"
"      <label>MQTT Broker IP (with Port)</label>"
"      <input type='text' name='ip' value='%s' placeholder='e.g. 192.168.1.20:1883'>"
"      <label>MQTT Username</label>"
"      <input type='text' name='user' value='%s'>"
"      <label>MQTT Password</label>"
"      <input type='password' name='pass' value='%s'>"
"      <input type='submit' value='Save & Reboot'>"
"    </form>"
"    <div class='note'>Device will reboot after saving.</div>"
"  </div>"
"</body>"
"</html>";